# Generated by Django 3.2.16 on 2022-10-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIPS', models.IntegerField(null=True)),
                ('Admin', models.CharField(max_length=80, null=True)),
                ('Province_State', models.CharField(max_length=80, null=True)),
                ('Country_Region', models.CharField(max_length=80, null=True)),
                ('Last_Update', models.DateTimeField(null=True)),
                ('Lat', models.FloatField(null=True)),
                ('Long', models.FloatField(null=True)),
                ('Confirmed', models.IntegerField(null=True)),
                ('Deaths', models.IntegerField(null=True)),
                ('Recovered', models.IntegerField(null=True)),
                ('Active', models.IntegerField(null=True)),
                ('Combined_Key', models.CharField(max_length=80, null=True)),
                ('Incident_Rate', models.FloatField(null=True)),
                ('Case_Fatality_Ratio', models.FloatField(null=True)),
            ],
        ),
    ]
